#!/bin/sh

usage() {
	cat <<EOF
usage:	$(basename "$0") [options] root

	-a <arch>
	-c <cachedir>
	-m <mirror>
EOF
}

while getopts 'a:c:d:m:' opt; do
   case "$opt" in
       a) arch=$OPTARG;;
       c) cachedir=$OPTARG;;
       m) mirror=$OPTARG;;
       *) usage >&2; exit 1;;
   esac
done
shift $((OPTIND - 1))

if [ $# -ne 1 ]; then
	usage >&2
	exit 1
fi

root=$1
arch=${arch-$(uname -m)}
cachedir=${cachedir-${XDG_CACHE_HOME-HOME/.cache/archbootstrap}}
mirror=${mirror-https://mirrors.kernel.org/archlinux/}
archive=$cachedir/$(
	curl -s "${mirror}iso/latest/" | \
	grep -o "archlinux-bootstrap-[0-9]\{4\}\.[0-9]\{2\}\.[0-9]\{2\}-$(uname -m).tar.gz" | \
	head -n1)

mkdir -p "$cachedir"

curl -# -C - -o "$archive" "${mirror}iso/latest/$(basename "$archive")"
curl -# -C - -o "$archive.sig" "${mirror}iso/latest/$(basename "$archive").sig"

gpg --verify "$archive.sig" "$archive" || exit $?

sudo sh <<EOF
mkdir -p "$root"
tar xf "$archive" -C "$root" --strip-components 1
EOF

echo

cat <<EOF
post-install ideas:

	sed -i 's/^CheckSpace/#CheckSpace/' /etc/pacman.conf
	echo 'Server = $mirror\$repo/os/\$arch' > /etc/pacman.d/mirrorlist
	echo 'en_US.UTF-8 UTF-8' > /etc/locale.gen
	echo LANG="en_US.UTF-8" > /etc/locale.conf
	ln -s /usr/share/zoneinfo/UTC /etc/localtime

	pacman-key --init
	pacman-key --populate archlinux
	pacman -Syu --needed base --ignore=linux
	locale-gen
EOF
